### ISSUE TITLE
Something wrong in the Anatomy part

### ISSUE THREAD

**Issue by bbontempo** [EightShapes/specs-plugin#170] opened 2024-07-10 10:22 UTC
### Description

There is something wrong with the formatting of the Anatomy part when generating specs.

### Steps to reproduce

I'll send a link to the file

### Screenshot
<img width="757" alt="Screenshot 2024-07-10 at 11 21 14" src="https://github.com/EightShapes/specs-plugin/assets/110467720/6eb11103-2759-4f00-8a09-54a82034365e">

### Additional context

It's misaligned and different of what it was.

### Defect log

File link: https://www.figma.com/design/8V8af0rNr7v5iHOI3K5ouc/Untitled?node-id=0-1&t=WNyOlkfiMV9BJh97-1

**Comment by nathanacurtis** [comment] 2024-07-10 12:21
@bbontempo 
Thanks for submitting. Yes, unfortunately, this is an unresolved defect due to the plugin wide refactor necessary when Figma's API when to asynchronously loaded pages (earlier this year, to improve file performance). It's an #155 issue already in the backlog, and I've not been able to prioritize it. I'll close this request since it's a duplicate of that one.

I appreciate you submitting,
Nathan

**Closed by nathanacurtis** 2024-07-10 12:21 UTC
