### ISSUE TITLE
"Callback failed to return a valid handle" (2)

### ISSUE THREAD

**Issue by DinaSporer** [EightShapes/specs-plugin#75] opened 2023-05-31 20:45 UTC
### Description

The plugin encountered an error

### Steps to reproduce

1. Select component instance
2. Press "Create Specs"
3. Get error message

### Screenshot

Output stalls at:
<img width="1230" alt="Screenshot 2023-05-31 at 1 45 05 PM" src="https://github.com/EightShapes/specs-plugin/assets/59457633/ec7b2a3d-00e7-4395-a6fc-53140885979b">

### Additional context

{Add any other context about the problem here}

### Defect log
<img width="679" alt="Screenshot 2023-05-31 at 1 44 27 PM" src="https://github.com/EightShapes/specs-plugin/assets/59457633/829d75d9-fc35-494e-a304-6252f8150790">

**Comment by nathanacurtis** [comment] 2023-06-01 11:42
May be related to/same defect as #74 #77

**Comment by amandasmcvey** [comment] 2023-06-01 15:22
> @DinaSporer
> 
> Well that's a defect message I've not encountered before. Would you be able to provide access to a view-only version of your component so that I can inspect and reproduce the error?
> 
> If you'd like to keep it confidential, you could DM me on the Slack community group linked from the plugin page, or ... perhaps another Slack where you know where to find me ;)

Next day with cycled PC and Figma, and I'm no longer having the issue. 
Some info when I did see the issue though: the plugin failed similarly for every component I tried to create a spec from. Will provide more info if it happens again.

**Comment by nathanacurtis** [comment] 2023-06-01 19:00
Update: Per Figma developer community, "Figma had identified the issue yesterday and had pushed out a fix". However, I'm still experiencing the issue locally.

**Comment by nathanacurtis** [comment] 2023-06-01 23:48
## Resolution

After working with a developer Figma's API dev team, who graciously Zoom'ed with me to see what was going on, he acknowledged that fixing the issue was ongoing. He later pushed a fix this evening, and I've confirmed the issue is no longer occurring in production. 

## Next steps

Please close your browser/Figma app, open it, and continue work. If the issue persists, reopen the issue. 

Thanks for reporting!

**Closed by nathanacurtis** 2023-06-01 23:48 UTC
Labels: defect

**Comment by amandasmcvey** [comment] 2023-06-01 23:50
Thank you!
