### ISSUE TITLE
"Callback failed to return a valid handle" (1)

### ISSUE THREAD

**Issue by regoremor** [EightShapes/specs-plugin#74] opened 2023-05-31 20:08 UTC
### Description

Callback failed to return a valid handle

### Screenshot

<img width="970" alt="Screen Shot 2023-05-31 at 4 06 00 PM" src="https://github.com/EightShapes/specs-plugin/assets/9708927/d47866e9-c436-480a-871c-988f751ae6c7">

**Comment by nathanacurtis** [comment] 2023-06-01 11:42
May be related to/same defect as #75 #77

**Comment by regoremor** [comment] 2023-06-01 16:15
Hi @nathanacurtis I tried again today and it generated the documentation. I will let you know if I detect any problems when creating new components. Thank you.

<img width="333" alt="Screen Shot 2023-06-01 at 12 13 41 PM" src="https://github.com/EightShapes/specs-plugin/assets/9708927/2662d0db-bbc8-4e52-833b-efdeb8eae602">

**Comment by nathanacurtis** [comment] 2023-06-01 23:48
## Resolution

After working with a developer Figma's API dev team, who graciously Zoom'ed with me to see what was going on, he acknowledged that fixing the issue was ongoing. He later pushed a fix this evening, and I've confirmed the issue is no longer occurring in production. 

## Next steps

Please close your browser/Figma app, open it, and continue work. If the issue persists, reopen the issue. 

Thanks for reporting!

**Closed by nathanacurtis** 2023-06-01 23:48 UTC
Labels: defect, Props
