### ISSUE TITLE
Text style not applied for Token Studio and raw values

### ISSUE THREAD

**Issue by dlewand691** [EightShapes/specs-plugin#146] opened 2024-03-20 20:18 UTC
### Description

After running the plugin, a text style is not added to the Token Studio reference or the raw value that's added to the end. Please update to apply a text style so these data points can be customized.

### Screenshot

![CleanShot 2024-03-20 at 16 18 05@2x](https://github.com/EightShapes/specs-plugin/assets/1159913/e3b9df1c-a6dd-4539-b82d-ab31c5be1774)

**Comment by nathanacurtis** [comment] 2024-03-20 20:36
@dlewand691 That's interesting. I'm unsure if I'd be able to reproduce that myself for I'm not sure what's triggering that display. Would you be willing to share a sample Figma file (view only) that I'd be able to inspect and test against?

**Comment by dlewand691** [comment] 2024-03-21 14:26
@nathanacurtis Sure! See if you can get to this link. It's very much a work in progress but you'll see the areas there: https://www.figma.com/file/B9Urc5mN5LvMtFoym52YwK/Web-design-system-visuals?type=design&node-id=48%3A1037&mode=design&t=B8h3emBjww6w810N-1

**Comment by nathanacurtis** [comment] 2024-03-21 17:07
@dlewand691 I'm inquiring with the TS studio team about the meaning and implications of the broken link icon in the TS studio interface and it's impact on reading that plugin's "shared data" using by the specs plugin.
![image](https://github.com/EightShapes/specs-plugin/assets/1165904/4eed85f1-0d0a-4759-823a-4c20a3981b1a)

**Comment by nathanacurtis** [comment] 2024-03-21 20:36
@dlewand691 TS reports that:
> "(the broken link symbol) should mean that there is a token applied that TS studio cannot find (in the activated token sets)."

Can you check on your side that your TS tokens are setup properly?

**Comment by Danny-Cognizant** [comment] 2024-03-21 21:00
@nathanacurtis I'm not using TS in the current setup. I was initially but stopped and removed it because it was getting overly complicated. I guess may there's some lingering leftovers? I'll see what I can do to resolve this.

**Comment by dlewand691** [comment] 2024-03-22 16:58
@nathanacurtis I was able to go through all my components and fix them easier than I thought. There are no broken links anywhere now. One issue remains though, the raw value at the end of the label is still not linked to a style.

![CleanShot 2024-03-22 at 12 57 09@2x](https://github.com/EightShapes/specs-plugin/assets/1159913/c0715dcc-0cfd-4f9d-bc78-ee1698c525a6)

**Comment by dlewand691** [comment] 2024-03-22 20:08
More formatting recommendation/requests...

- Remove the extra space before the colon of Attribute Property
- Add a / between the group name and variable name
- Add ( ) around raw variable

![CleanShot 2024-03-22 at 16 04 44@2x](https://github.com/EightShapes/specs-plugin/assets/1159913/1a1571f2-3054-4662-ac6c-e2119d81d519)

**Comment by nathanacurtis** [comment] 2024-03-25 11:39
Resolving here. Added #149 as separate request.

**Closed by nathanacurtis** 2024-03-25 11:39 UTC
Labels: DEFECT, Anatomy, Attribute
