### ISSUE TITLE
The plugin don´t do creat specs

### ISSUE THREAD

**Issue by gustavo-ross** [EightShapes/specs-plugin#121] opened 2023-11-08 13:17 UTC
### Description

the plugin did not create the specs for a specific element, I tested it on another and it worked normally

### Steps to reproduce

Just run the plugin in the component "Download app - Horizontal"

### Screenshot

![Captura de tela 2023-11-08 101227](https://github.com/EightShapes/specs-plugin/assets/150253416/56521d3b-9ae5-48b9-addd-3f8ac1600595)
![Captura de tela 2023-11-08 101255](https://github.com/EightShapes/specs-plugin/assets/150253416/8e0670f5-225f-44e2-8dc5-6b65de467654)

### Additional context

Nothing to add

### Defect log

in remove: The node with id "919:31057" does not exist

**Comment by nathanacurtis** [comment] 2023-11-08 14:43
@gustavo-ross 

Thanks for your submission.

So, during the construction of the Layout and spacing section, it produced one exhibit (your screenshot) but failed to go deeper and resulted in the error `The node ... does not exist`? If so, I'm unsure what about your frame and it's nested layers would be triggering that error.

If it's possible for you to provide access to the `Download app - Horizontal` frame and it's content in a view-only file, I'd be happy to troublesheet. You can link here, or if you'd prefer to privately DM, you can access the [EightShapes Specs Slack](https://join.slack.com/t/eightshapes-specs/shared_invite/zt-1w4k19pj7-viPHKW8045zak64u~lH4yA) and DM me the link there.

**Comment by gustavo-ross** [comment] 2023-11-08 18:45
Sorry for the delay, here is the link:
https://www.figma.com/file/verrIuFA5CNoqctBKQadYf/Test-Specs?type=design&node-id=0%3A1&mode=design&t=s11cpxUnqISf7C4I-1

**Comment by nathanacurtis** [comment] 2023-11-08 18:52
@gustavo-ross I've accessed your file and validated that running the plugin on either the component set OR an instance is throwing the error in both cases. I'm unsure immediately what the issue is, and continue troubleshooting in the coming day.

**Comment by gustavo-ross** [comment] 2023-11-08 19:10
Okay, thanks for the support.

**Comment by nathanacurtis** [comment] 2023-11-09 21:23
@gustavo-ross I've narrowed the issue to an unpredictable behavior in the Figma API, and I'll be issuing a fix in the days to come. 

In the meantime, to run the plugin without it failing and instead producing the remaining layout and spacing specs, change the top level node from `WRAP` to `HORIZONTAL` layout (this change shouldn't impact your design).

**Comment by nathanacurtis** [comment] 2023-11-10 19:51
@gustavo-ross The fix has been released, and your component should run without issue as-is. Note that you will have to restart the Figma app (or browser) to experience the update.

**Comment by gustavo-ross** [comment] 2023-11-10 20:09
It worket, thakyou for the support Nathan!

**Closed** 2023-11-22 17:38 UTC
Labels: FIXED-To be released
