### ISSUE TITLE
"Callback failed to return a valid handle" (3)

### ISSUE THREAD

**Issue by timothynguyen22** [EightShapes/specs-plugin#77] opened 2023-06-01 03:56 UTC
### Description

The plugin encounters an error when I try creating a spec

### Steps to reproduce

1. Click component
2. Run EightShapes
3. Click create specs
4. Error message appears 

### Screenshot
![Untitled](https://github.com/EightShapes/specs-plugin/assets/66104918/8b334d9e-0b6a-4297-8c06-faf853844b50)

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

3

### Screenshot

{If applicable, add screenshots such as the Figma canvas, layer panel or design panel}

### Additional context

{Add any other context about the problem here}

### Defect log

{Copy the message from the browser/Figma console, if relevant}

**Comment by nathanacurtis** [comment] 2023-06-01 11:29
@timothynguyen22 

Would you be able to provide access to a view-only version of your component so that I can inspect and reproduce the error? If you'd like to keep it confidential, you could DM me on the Slack community group linked from the plugin page.

**Comment by nathanacurtis** [comment] 2023-06-01 19:00
Update: Per Figma developer community, "Figma had identified the issue yesterday and had pushed out a fix". However, I'm still experiencing the issue locally.

**Comment by nathanacurtis** [comment] 2023-06-01 23:48
## Resolution

After working with a developer Figma's API dev team, who graciously Zoom'ed with me to see what was going on, he acknowledged that fixing the issue was ongoing. He later pushed a fix this evening, and I've confirmed the issue is no longer occurring in production. 

## Next steps

Please close your browser/Figma app, open it, and continue work. If the issue persists, reopen the issue. 

Thanks for reporting!

**Closed by nathanacurtis** 2023-06-01 23:48 UTC
Labels: defect
