### ISSUE TITLE
Plugin fails while generating Properties display

### ISSUE THREAD

**Issue by TWFnews** [EightShapes/specs-plugin#76] opened 2023-06-01 03:55 UTC
### Description
Please assist me in fixing the mistake; I'm using a plugin to create component details.

### Screenshot
https://github.com/EightShapes/specs-plugin/assets/112161215/203d3d96-c644-443b-b138-d3464c472f41

### Defect log
Figma Desktop app Ver 116.9.5

**Comment by nathanacurtis** [comment] 2023-06-01 11:28
@TWFnews Thanks for the video!

@regoremor 

Would you be able to provide access to a view-only version of your component so that I can inspect and reproduce the error? If you'd like to keep it confidential, you could DM me on the Slack community group linked from the plugin page.

**Comment by nathanacurtis** [comment] 2023-06-01 23:48
## Resolution

After working with a developer Figma's API dev team, who graciously Zoom'ed with me to see what was going on, he acknowledged that fixing the issue was ongoing. He later pushed a fix this evening, and I've confirmed the issue is no longer occurring in production. 

## Next steps

Please close your browser/Figma app, open it, and continue work. If the issue persists, reopen the issue. 

Thanks for reporting!

**Closed by nathanacurtis** 2023-06-01 23:48 UTC
Labels: defect, Props
